# Generated by Django 3.0.9 on 2021-05-28 13:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('sort', models.CharField(blank=True, max_length=10, verbose_name='Сортировка')),
                ('anons', models.BooleanField(default=False, verbose_name='На главную')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Специалистам COVID-19',
                'verbose_name_plural': 'Специалистам COVID-19',
            },
        ),
    ]
