# Generated by Django 3.0.9 on 2021-04-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201225_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(default=True, max_length=300, verbose_name='Опубликовать'),
        ),
    ]
