# Generated by Django 3.0.9 on 2021-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210609_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
