# Generated by Django 3.0.9 on 2021-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mos_doc_url',
            field=models.CharField(default='', max_length=500, verbose_name='Ссылка на московского врача'),
            preserve_default=False,
        ),
    ]
