# Generated by Django 3.0.9 on 2021-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_mos_doc_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='degree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mos_doc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Московский врач'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mos_doc_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на московского врача'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rank',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ученое звание'),
        ),
    ]
