# Generated by Django 3.0.9 on 2021-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210519_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='category',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='rank',
        ),
        migrations.AddField(
            model_name='employees',
            name='accreditation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Аккредитация'),
        ),
        migrations.AddField(
            model_name='employees',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Квалификационная категория'),
        ),
        migrations.AddField(
            model_name='employees',
            name='speciality_akk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность по аккредитации'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mos_doc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Статус Московский врач'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='speciality',
            field=models.CharField(max_length=500, verbose_name='Специальность по сертификату'),
        ),
    ]
