# Generated by Django 3.0.9 on 2021-07-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contractsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Номер контракта')),
                ('contract_date', models.DateField(verbose_name='Дата контракта')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракт',
            },
        ),
        migrations.CreateModel(
            name='periodsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование периода')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Период',
            },
        ),
        migrations.CreateModel(
            name='managementApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Учреждение|Рук-ль группы')),
                ('man_key_contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_contractApp_fk', to='schoolNursesApp.contractsApp', verbose_name='Контракт')),
                ('man_key_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_periodApp_fk', to='schoolNursesApp.periodsApp', verbose_name='Период')),
            ],
        ),
        migrations.AddField(
            model_name='contractsapp',
            name='key_periods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodApp_fk', to='schoolNursesApp.periodsApp', verbose_name='Период'),
        ),
    ]
