# Generated by Django 3.0.9 on 2021-07-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('Ж', 'Ж'), ('М', 'М')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=100, verbose_name='СНИЛС')),
                ('reg_key_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_managementApp_fk', to='schoolNursesApp.managementApp', verbose_name='Учреждение|Рук-ль группы')),
            ],
        ),
    ]
