# Generated by Django 3.0.9 on 2021-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=500, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=500, verbose_name='Отчество')),
                ('place_job', models.CharField(max_length=500, verbose_name='Место работы')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('degree', models.CharField(max_length=500, verbose_name='Ученая степень|Научное звание')),
                ('location', models.CharField(max_length=500, verbose_name='Регион')),
                ('phone_job', models.CharField(max_length=500, verbose_name='Рабочий телефон')),
                ('phone', models.CharField(blank=True, max_length=500, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=500, verbose_name='E-mail')),
                ('school', models.CharField(choices=[('Школа профессора Борисова: «Перспективы лечения больных туберкулезом в ближайшие десятилетия»', 'Школа профессора Борисова: «Перспективы лечения больных туберкулезом в ближайшие десятилетия»'), ('Школа академика Литвинова «Современные методы этиологической диагностики микобактериальной инфекции»', 'Школа академика Литвинова «Современные методы этиологической диагностики микобактериальной инфекции»'), ('«Особенности профилактики и лечения детского туберкулеза в мегаполисе»', '«Особенности профилактики и лечения детского туберкулеза в мегаполисе»'), ('«Организация работы среднего медицинского персонала в период пандемии»', '«Организация работы среднего медицинского персонала в период пандемии»')], max_length=300, verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Регистрация на конференицию',
                'verbose_name_plural': 'Регистрация на конференицию',
            },
        ),
    ]
