# Generated by Django 3.0.9 on 2021-06-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0002_auto_20210612_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='degree',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ученая степень|Научное звание'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=500, verbose_name='E-mail'),
        ),
    ]
