# Generated by Django 3.0.9 on 2021-07-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contractsNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Номер контракта')),
                ('contract_date', models.DateField(verbose_name='Дата контракта')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракт',
            },
        ),
        migrations.CreateModel(
            name='managementNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Учреждение | Организатор группы')),
                ('man_key_contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_contractNurses_fk', to='trainingNurses.contractsNurses', verbose_name='Контракт')),
            ],
        ),
        migrations.CreateModel(
            name='periodsNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование периода')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Период',
            },
        ),
        migrations.CreateModel(
            name='personNurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('Ж', 'Ж'), ('М', 'М')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=100, verbose_name='СНИЛС')),
                ('per_key_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_managementNurses_fk', to='trainingNurses.managementNurses', verbose_name='Учреждение|Рук-ль группы')),
                ('per_key_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_periodNurses_fk', to='trainingNurses.managementNurses', verbose_name='Учреждение|Рук-ль группы')),
            ],
        ),
        migrations.AddField(
            model_name='managementnurses',
            name='man_key_periods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_periodNurses_fk', to='trainingNurses.periodsNurses', verbose_name='Период'),
        ),
    ]
