# Generated by Django 3.0.9 on 2021-07-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingNurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnurses',
            name='per_key_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_periodNurses_fk', to='trainingNurses.periodsNurses', verbose_name='Период обучения'),
        ),
    ]
