# Generated by Django 3.0.9 on 2021-07-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingNurses', '0002_auto_20210706_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnurses',
            name='per_key_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='per_contactNurses_fk', to='trainingNurses.contractsNurses', verbose_name='Контракт'),
            preserve_default=False,
        ),
    ]
