# Generated by Django 3.0.9 on 2021-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needToKnow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='know',
            options={'verbose_name': 'Это нужно знать', 'verbose_name_plural': 'Это нужно знать'},
        ),
        migrations.RemoveField(
            model_name='know',
            name='content',
        ),
        migrations.AddField(
            model_name='know',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='know',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
