# Generated by Django 3.0.9 on 2021-05-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needToKnow', '0003_auto_20210527_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='know',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
    ]
