# Generated by Django 3.0.9 on 2021-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needToKnow', '0004_auto_20210527_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='know',
            name='anons',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
        migrations.AddField(
            model_name='know',
            name='sort',
            field=models.CharField(blank=True, max_length=10, verbose_name='Сортировка'),
        ),
    ]
