# Generated by Django 3.0.9 on 2021-05-27 13:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needToKnow', '0005_auto_20210527_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='know',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент'),
        ),
    ]
