# Generated by Django 3.0.9 on 2021-01-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paidServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSunderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUC', models.CharField(max_length=500, verbose_name='Наименование подкатегории')),
                ('keyNameC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psundercategory', to='paidServices.PSCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
    ]
