# Generated by Django 3.0.9 on 2021-01-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paidServices', '0002_psundercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№ п/п')),
                ('code', models.IntegerField(verbose_name='Код услуги')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('keyNameCU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psservice', to='paidServices.PSunderCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Наименование услуги',
                'verbose_name_plural': 'Наименование услуги',
            },
        ),
    ]
