# Generated by Django 3.0.9 on 2021-01-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidServices', '0003_pslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pslist',
            name='code',
            field=models.CharField(max_length=300, verbose_name='Код услуги'),
        ),
        migrations.AlterField(
            model_name='pslist',
            name='number',
            field=models.CharField(max_length=100, verbose_name='№ п/п'),
        ),
        migrations.AlterField(
            model_name='pslist',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
    ]
