# Generated by Django 3.0.9 on 2021-04-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0002_auto_20210416_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='undercategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='undercategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='undercategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='undercategory',
            name='tree_id',
        ),
    ]
