# Generated by Django 3.0.9 on 2021-04-16 12:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0003_auto_20210416_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='anons',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='Ссылка на документ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UnderCategory',
        ),
    ]
