# Generated by Django 3.0.9 on 2021-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0004_auto_20210416_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ссылка на документ'),
        ),
    ]
