# Generated by Django 3.0.9 on 2021-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0005_auto_20210416_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование периода')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(verbose_name='Дата окончания обучения')),
            ],
            options={
                'verbose_name': 'Добавить период',
                'verbose_name_plural': 'Добавление периода',
            },
        ),
    ]
