# Generated by Django 3.0.9 on 2021-06-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0006_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Номер контракта')),
                ('contract_date', models.DateField(verbose_name='Дата контракта')),
                ('key_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_fk', to='schoolNurses.periods', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Добавление контракта',
            },
        ),
    ]
