# Generated by Django 3.0.9 on 2021-06-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0007_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='key_periods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_fk', to='schoolNurses.periods', verbose_name='Период'),
        ),
        migrations.CreateModel(
            name='form_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=300, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('Ж', 'Ж'), ('М', 'М')], max_length=1, verbose_name='Пол')),
                ('snils', models.CharField(max_length=100, verbose_name='СНИЛС')),
                ('reg_key_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_contract_fk', to='schoolNurses.contracts', verbose_name='Контракт')),
                ('reg_key_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_period_fk', to='schoolNurses.periods', verbose_name='Период')),
            ],
        ),
    ]
