# Generated by Django 3.0.9 on 2021-06-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0008_auto_20210624_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Учреждение|Рук-ль группы')),
                ('man_key_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_period_fk', to='schoolNurses.periods', verbose_name='Период')),
            ],
        ),
        migrations.AddField(
            model_name='form_registration',
            name='reg_key_management',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='reg_management_fk', to='schoolNurses.management', verbose_name='Учреждение|Рук-ль группы'),
            preserve_default=False,
        ),
    ]
