# Generated by Django 3.0.9 on 2021-06-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolNurses', '0009_auto_20210624_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='man_key_contracts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='man_contract_fk', to='schoolNurses.contracts', verbose_name='Контракт'),
            preserve_default=False,
        ),
    ]
