# Generated by Django 3.0.9 on 2021-06-17 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Добавить коференцию',
                'verbose_name_plural': 'Добавить коференцию',
            },
        ),
        migrations.CreateModel(
            name='schoolName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('conference_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='regConf.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Добавить школу',
                'verbose_name_plural': 'Добавить школу',
            },
        ),
        migrations.CreateModel(
            name='regSurname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=500, verbose_name='Фамилия')),
                ('school_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='regConf.schoolName', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Добавить участника',
                'verbose_name_plural': 'Добавить участника',
            },
        ),
        migrations.CreateModel(
            name='regPatronymic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(max_length=500, verbose_name='Отчество')),
                ('surname_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patronymic', to='regConf.regSurname', verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='regName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('surname_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='regConf.regSurname', verbose_name='Имя')),
            ],
        ),
    ]
