# Generated by Django 3.0.9 on 2021-06-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regConf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpatronymic',
            name='surname_key',
        ),
        migrations.AddField(
            model_name='regpatronymic',
            name='name_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patronymic', to='regConf.regName', verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
