# Generated by Django 3.0.9 on 2021-06-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regConf', '0002_auto_20210618_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='regOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_job', models.CharField(max_length=500, verbose_name='Место работы')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('degree', models.CharField(blank=True, max_length=500, verbose_name='Ученая степень|Научное звание')),
                ('location', models.CharField(max_length=500, verbose_name='Регион')),
                ('phone_job', models.CharField(max_length=500, verbose_name='Рабочий телефон')),
                ('phone', models.CharField(blank=True, max_length=500, verbose_name='Телефон')),
                ('email', models.CharField(max_length=500, verbose_name='E-mail')),
                ('name_patronymic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='regConf.regPatronymic', verbose_name='Остальные поля')),
            ],
        ),
    ]
