# Generated by Django 3.0.9 on 2021-06-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regConf', '0003_regother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regname',
            name='surname_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regsurname', to='regConf.regSurname', verbose_name='Имя'),
        ),
    ]
