# Generated by Django 3.0.9 on 2021-06-02 12:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smi', '0002_auto_20210415_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='smiVideoclips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на внешний источник')),
                ('sort', models.CharField(blank=True, max_length=10, verbose_name='Сортировка')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Видеоролик',
                'verbose_name_plural': 'Видеоролики',
            },
        ),
    ]
