# Generated by Django 3.0.9 on 2020-12-25 05:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('amb_help', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Амбулаторная помощь')),
                ('stac_help', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Стационарная помощь')),
                ('tel_cnt_br', models.CharField(blank=True, max_length=200, verbose_name='Телефоны контакта филиала')),
                ('tel_hotline', models.CharField(blank=True, max_length=100, verbose_name='Горячая линия')),
                ('secretary', models.CharField(blank=True, max_length=200, verbose_name='Секретарь тел./факс')),
                ('tel_reg_ad', models.CharField(blank=True, max_length=100, verbose_name='Регистратура(взр-ое.отд.)')),
                ('tel_reg_ch', models.CharField(blank=True, max_length=100, verbose_name='Регистратура(дет-ое.отд.)')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Электронная почта')),
                ('opening_hour', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Режим работы')),
                ('head', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Руководитель филилал')),
                ('tel_head', models.CharField(blank=True, max_length=100, verbose_name='Телефоны контакта рукод-ва')),
                ('reception', models.CharField(blank=True, max_length=100, verbose_name='Приемная')),
                ('opening_hour_head', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Часы работы заведующего')),
                ('substitute', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Заместитель/телефон/часы приема')),
                ('substitute_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация о руководителях')),
                ('history', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткая история')),
                ('territory', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Территориальные районы')),
                ('body_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация о корпусах')),
                ('stac_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация о стационаре')),
                ('doctors_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Количество врачей')),
                ('separation_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация по кабинетам')),
                ('type_help', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Виды помощи')),
                ('equipping_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Оснощение филиала')),
                ('medicines_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация о лекарствах')),
                ('other_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Иная информация')),
                ('image_title', models.ImageField(blank=True, upload_to='branches/', verbose_name='Фото заголовка')),
                ('image_head', models.ImageField(blank=True, upload_to='branches/', verbose_name='Фото руководителя')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('division', models.CharField(blank=True, max_length=300, verbose_name='Подразделение (Наименование)')),
                ('job', models.CharField(blank=True, max_length=200, verbose_name='Штатная должность (Наименование)')),
                ('vyz', models.CharField(blank=True, max_length=300, verbose_name='ВУЗ')),
                ('date_vyz', models.CharField(blank=True, max_length=100, verbose_name='Дата окончания')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('sertif', models.CharField(blank=True, max_length=100, verbose_name='Сертификат')),
                ('date_sertif', models.CharField(blank=True, max_length=100, verbose_name='Дата выдачи')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Степень')),
                ('keyBranches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='structure.Branches', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='GalleryBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='branches/', verbose_name='Фото/Схема проезда')),
                ('location_map', models.BooleanField(default=False, verbose_name='Схема проезда')),
                ('keyBranches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='structure.Branches')),
            ],
        ),
    ]
