# Generated by Django 3.0.9 on 2021-04-07 12:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20201123_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='branches',
            name='anons_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='branches',
            name='otdel_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Информация по отделениям'),
        ),
    ]
